version: "3.8"
name: shuffler

services:
  shuffler-client:
    container_name: shuffler-client
    build:
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "443:3000"
      - "3000:3000"
    networks:
      - host

networks:
  host:
    name: host
    external: true